### PR TITLE
Adding GitHub actions workflow

### PR DESCRIPTION
**Pull request by hecko**
Adding GitHub actions workflow to test-compile all Arduino versions of Optiboot against GNU toolchain in Debian 11

### CODE REVIEW

**Comment by mcuee** [comment]
This is pretty good.

However, it is better not to use the avr-gcc toolchain from Debian 11 which is probably not proven. It would be good to use Microchip toolchain based on avr-gcc 5.4.0 for this github action (second choice is Microchip toolchain based on avr-gcc 7.3.0).

**Comment by mcuee** [comment]
The other thing is to save the result files (elf, hex and lst).

**Comment by hecko** [comment]
Where do i find ooficial source for microchip toolchain with avr gcc 5.4.0?

**Comment by mcuee** [comment]
> Where do i find ooficial source for microchip toolchain with avr gcc 5.4.0?

Click Archives tab in the following link.
https://www.microchip.com/en-us/tools-resources/develop/microchip-studio/gcc-compilers
https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/SoftwareLibraries/Firmware/avr8-gnu-toolchain-3.6.2.1778-linux.any.x86_64.tar.gz

**Comment by WestfW** [comment]
> Where do i find ooficial source for microchip toolchain with avr gcc 5.4.0?

beats me.  Atmel was not very good at keeping a current source repository available, and by most accounts, Microchip is worse.

mcuee's links appear to be binaries only. :-(

**Comment by hecko** [comment]
Ill rewrite this and create a new PR.

**Comment by mcuee** [comment]
> > Where do i find ooficial source for microchip toolchain with avr gcc 5.4.0?
> 
> beats me. Atmel was not very good at keeping a current source repository available, and by most accounts, Microchip is worse.
> 
> mcuee's links appear to be binaries only. :-(

Indeed the link is binary only. Last time Atmel seems to distribute the source [here](http://distribute.atmel.no/tools/opensource/Atmel-AVR-GNU-Toolchain/) (dead link now) as per Arduino people.
https://github.com/arduino/toolchain-avr

In any case I think @hecko is only asking the link for binary package and not the source package. But yes Microchip has to follow the license and publish the source archive somewhere. I tend to believe it is somwhere in the Microchip website but the links are lost in the transition from Atmel to Microchip.

**Comment by mcuee** [comment]
If we look at Debian testing packages, they do incorporate Atmel 3.6.2 toolchain patches.
https://packages.debian.org/bookworm/gcc-avr
https://packages.debian.org/bookworm/binutils-avr
https://packages.debian.org/bookworm/avr-libc

**Pull request closed without merging**
