### PR TITLE
contribute fix for hardware UART 1, 2, and 3

### PR DESCRIPTION
**Pull request by dmjlambert**
Hi
I would like to contribute to Optiboot/optiboot,   In this version I fixed hard coded bit definitions to make compatible with HW UART 1, 2, and 3.   Changes are in optiboot.c with corresponding definitions in pin_defs.h.   In version 6.2 it does not work for UARTs higher than 0.  Also removed some ^L characters in the optiboot.c.  Added support for ATmega32U4, which uses UART1.
Regards
David

### CODE REVIEW

**Comment by dmjlambert** [comment]
I realized I had a typo in the pin_defs.h section for UART == 2
define UART_SRC UCSR0C should have been define UART_SRC UCSR2C

I have corrected it in dmjlambert/optiboot but I did so after this pull request.   So I'm not sure how to update the pull request, or if the correction should be handled as a separate pull request, or if just this comment will be adequate.  I am new to GitHub.

**Comment by WestfW** [comment]
Is this the only part that is actually a fix?  The other changes look cosmetic...

-atmega1280: CFLAGS += $(COMMON_OPTIONS) -DBIGBOOT $(UART_CMD)
+atmega1280: CFLAGS += $(COMMON_OPTIONS) -DBIGBOOT $(UARTCMD)

**Comment by dmjlambert** [comment]
Hi Bill,

No, actually the other changes are necessary.

If you look at this line for example:

UART_SRB = _BV(RXEN0) | _BV(TXEN0);

You can see that it is loading whatever the appropriate SRB register is, with specific bit values which have been or’d together.  

Which UART exactly it is trying to load depends on what value was picked in pin_defs.h when the UART=something has been given on the make command line.  For example if UART=0 then UCSR0B is the register and you are loading it with the bit RXEN0 or’d withTXEN0.  So far, so good.  

Now, what happens if you are trying to use UART=1 is UCSR1B is the register selected and defined as UART_SRB in the pin_defs.h, BUT you are still loading UCSR1B with the bit values from UART0, RXEN0 and TXEN0 bits, instead of the correct bits which are RXEN1 and TXEN1. 

So, we fix this by making the UART registers variables as set by the UART=something make command line setting, AND we also make the corresponding bits variables which correspond to the correct register at the same time.   So you see the larger number of settings in pin_defs.h which are used by lines like this in optiboot.c:

UART_SRB = _BV(UART_SRB_RXEN) | _BV(UART_SRB_TXEN);

This whole problem would not have been very obvious before when trying to compile for a multi-UART processor like the ATmega1280 because it will successfully compile because the bits for UART0 are still defined for the chip when you are trying to use UART1.  The compiled Optiboot won’t actually work to upload a sketch using UART1 on the processor, but the bootloader itself should compile and burn on the chip just fine.  

What made it stand out is when I tried to compile Optiboot for a processor which has only one UART, but it is named UART1, and there is no UART0 on that chip at all.   The ATmega32U4.  

Regards
David

**Comment by dmjlambert** [comment]
Hi
I need to clarify one point.   The bit numbers may actually be the same for each UART register's bits, so as long as that happens to be true for all AVR's it may actually compile and work as a matter of coincidence.  This coincidence works on ATmega1280.     But to be technically correct the bits by defined name for UART0 need to be loaded in the UART0 register, the bits for UART1 need to be loaded in UART1 register, and so on.  The problem reveals itself on other AVRs such as ATmega32U4.

**Comment by WestfW** [comment]
> The bit numbers may actually be the same for each UART register's bits...

They had better be, or all sorts of other things are likely to break.


> But to be technically correct the bits by defined name for UART0 need to be loaded in the UART0 register, the bits for UART1 need to be loaded in UART1 register, and so on.

Technically, Atmel made a bad decision to name the same bits in different instances of a peripheral with different names.  It really annoys me (especially with things like PORTC3), disguises the equality of the multiple uarts, and is incompatible with the "modern" trend to use "uart0base->sra & UART_TXC" syntax to handle such things (used on ARM chips (nearly required by CMSIS), and on the Atmel XMEGA chips.)   If there are multiple uarts with different implementations, the bits are as likely to change which register they're in as they are which bit positions they have.  (this happens in Atmega8, and some ARM chips have USART and UART peripherals.)  Grr.


> The problem reveals itself on other AVRs such as ATmega32U4.



But only because the 32u4 didn't define a UART0 (Why, Atmel, Why?), not because there are conflicting bit definitions for different uarts...

I'll probably decline this pull request, and make it into two separate issues/patches.  One to cover the UARTCMD vs UART_CMD problem, and a second to handle the 32u4 "feature addition."

**Comment by dmjlambert** [comment]
Are you getting concerned about the code getting harder to read and understand if you implement my change using definitions to hold the bit numbers?  If so, perhaps it would be best to hard code the actual bit numbers instead of using the names like RXEN0 and TXEN0, etc.  It would accomplish the same thing and probably be more clear and easy.

**Comment by dmjlambert** [comment]
I have a better solution which I think you will like.  Do you know how I can delete or cancel my pull request I sent to you?

**Comment by WestfW** [comment]
I did submit, fix, and commit https://github.com/Optiboot/optiboot/issues/131
  I don't know how to cancel a pull request; presumably I can close it without merging it, perhaps tagging with "superseded" or something...

**Pull request closed without merging**
